---
title: "HW4"
author: "Ruijie Ma"
date: "2018/2/26"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(knitr)
library(foreign)
library(stringr)
library(plyr)
library(reshape2)
library(xtable)
```
##12.6(3,4)
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=T)
who1 <- who %>% gather(new_sp_m014:newrel_f65, key = "key", value = "cases", na.rm = TRUE)
glimpse(who1)
who2 <- who1 %>% mutate(key = stringr::str_replace(key, "newrel", "new_rel"))
who3 <- who2 %>% separate(key, c("new", "type", "sexage"), sep = "_")
b <- select(who3,country,iso2,iso3)
b<-distinct(b)
b %>% group_by(country) %>% filter(n()>1)
b
who5 <-who3 %>% select(-new,-iso2,-iso3) %>% separate(sexage,c("sex","age"),sep=1,)

who5 <- who5 %>% group_by(country,year,sex)
who5 %>% summarise(cases = sum(cases)) %>% unite(country_sex, country, sex, remove = FALSE)
ggplot(who5,aes(year,cases))+geom_line()+geom_point(aes(color=country))
```
## 10.5(5) the code"enframe" can create a data frame by using vector
```{r setup ,include=FALSE}
knitr::opts_chunk$set(echo=T)
vec<-c(name="jerry",age=21)
a<-enframe(vec)
a
```
##Table4 -> Table6
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=T)
library(tidyverse)
library(dplyr)
library(foreign)
library(stringr)
library(plyr)
library(reshape2)
pew <- read.spss("/Users/ruijie/Ma415/tidy-data-master/data/pew.sav")
pew <- as.data.frame(pew)


religion <- pew[c("q16", "reltrad", "income")]
religion$reltrad <- as.character(religion$reltrad)
religion$reltrad <- str_replace(religion$reltrad, " Churches", "")
religion$reltrad <- str_replace(religion$reltrad, " Protestant", " Prot")
religion$reltrad[religion$q16 == " Atheist (do not believe in God) "] <- "Atheist"
religion$reltrad[religion$q16 == " Agnostic (not sure if there is a God) "] <- "Agnostic"
religion$reltrad <- str_trim(religion$reltrad)
religion$reltrad <- str_replace_all(religion$reltrad, " \\(.*?\\)", "")

religion$income <- c("Less than $10,000" = "<$10k", 
  "10 to under $20,000" = "$10-20k", 
  "20 to under $30,000" = "$20-30k", 
  "30 to under $40,000" = "$30-40k", 
  "40 to under $50,000" = "$40-50k", 
  "50 to under $75,000" = "$50-75k",
  "75 to under $100,000" = "$75-100k", 
  "100 to under $150,000" = "$100-150k", 
  "$150,000 or more" = ">150k", 
  "Don't know/Refused (VOL)" = "Don't know/refused")[religion$income]

religion$income <- factor(religion$income, levels = c("<$10k", "$10-20k", "$20-30k", "$30-40k", "$40-50k", "$50-75k", 
  "$75-100k", "$100-150k", ">150k", "Don't know/refused"))

counts <- count(religion, c("reltrad", "income"))
names(counts)[1] <- "religion"

xtable(counts[1:10, ], file = "pew-clean.tex")

# Convert into the form in which I originally saw it -------------------------

raw <- dcast(counts, religion ~ income)
Table6<-gather(raw,variable,values,-religion)
names(Table6)[2]<-"income"
names(Table6)[3]<-"freq"
Table6<-arrange(Table6,religion)
```
##Table7 -> Table8
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE)
library(lubridate)
library(reshape2)
library(stringr)
library(plyr)
data <- read.csv("~/Ma415/tidy-data-master/data/data.csv")
data <- data[, c("year", "artist.inverted", "track", "time", "date.entered", "x1st.week", "x2nd.week", "x3rd.week", "x4th.week", "x5th.week", "x6th.week", "x7th.week", "x8th.week", "x9th.week", "x10th.week", "x11th.week", "x12th.week", "x13th.week", "x14th.week", "x15th.week", "x16th.week", "x17th.week", "x18th.week", "x19th.week", "x20th.week", "x21st.week", "x22nd.week", "x23rd.week", "x24th.week", "x25th.week", "x26th.week", "x27th.week", "x28th.week", "x29th.week", "x30th.week", "x31st.week", "x32nd.week", "x33rd.week", "x34th.week", "x35th.week", "x36th.week", "x37th.week", "x38th.week", "x39th.week", "x40th.week", "x41st.week", "x42nd.week", "x43rd.week", "x44th.week", "x45th.week", "x46th.week", "x47th.week", "x48th.week", "x49th.week", "x50th.week", "x51st.week", "x52nd.week", "x53rd.week", "x54th.week", "x55th.week", "x56th.week", "x57th.week", "x58th.week", "x59th.week", "x60th.week", "x61st.week", "x62nd.week", "x63rd.week", "x64th.week", "x65th.week", "x66th.week", "x67th.week", "x68th.week", "x69th.week", "x70th.week", "x71st.week", "x72nd.week", "x73rd.week", "x74th.week", "x75th.week", "x76th.week")]
names(data)[2] <- "artist"

data$artist <- iconv(data$artist, "MAC", "ASCII//translit")
data$track <- str_replace(data$track, " \\(.*?\\)", "")
names(data)[-(1:5)] <- str_c("wk", 1:76)
data <- arrange(data, year, artist, track)

long_name <- nchar(data$track) > 20
data$track[long_name] <- paste0(substr(data$track[long_name], 0, 20), "...")

Table7<-data
Table8<-gather(Table7,variable,value,-c(year,artist,track,time,date.entered))
names(Table8)[6]<-"week"
names(Table8)[7]<-"rank"
names(Table8)[5]<-"data"
Table8<-arrange(Table8,artist)
Table8<-filter(Table8,rank>0)

```